* Sajban: The Language of Knowledge

** Universal Distributed Computing: The /Silicone/ is the OS

Self-describing, asynchronous-logic, signature-authenticated
object-messages to build tomorrow's computer systems.

** Design

*** Philosophy

#+BEGIN_QUOTE
  - He who writes in blood and proverbs does not want to be read, but
    learnt by heart. :: F. Nietzsche
#+END_QUOTE

Sajban's design is guided by perfection, which is best embodied in
living organisms. In other words, sajban aims to be the sole framework
used for the coming hundreds of millions of years, notwithstanding
mankind's seemingly unstoppable obsession for self-destruction. Hence,
the entire architecture must leave absolutely no room for improvement by
the last major revision, which should be completed by the end of the
author's life expectancy.

*** Technicalities

**** Real Computer format

Computers do no understand text, which means /there is not a single
computer-code framework in existence today/. All of the prevalent
bronze-age-script-formated "pseudo-codes" in use today must first be
/parsed/ into logically-meaningful binary trees before computers can
make any use of them. This in turn brings /immense/ problems in terms of
correctness, performance, innovation and usability.

**** Self-describing objects - /Data/ is the database

All sajban code has object-like properties, in the true sense of Alan
Kay's 'object-oriented' expression. In practice this implies that any
sajban object carries its entire context - from the protocol needed to
use it to all its past 'states' , if any, and implicitely, all its
possible future transformations.

**** Correctness /is/ security

In contrast with today's pseudo-security systems such as SSL and SSH,
/sajban is as secure as logically possible/. This is accomplished by
using cryptograhic signatures on the object themselves instead of
securing the connections progagating them. Such a system offers
multi-signatures capability and lets users keep their keys in cold
storage most of the time. Combined with its object-like properties,
sajban becomes a natural fit for ultra-secure multi-airgaps and
multi-key-holders systems.

*** Notes
**** Name

Sajban is lojban for 'Knowledge Language'. Lojban is very close in
spirit, and both projects can be thought of two subfields of the same
science: /communication logic/.

*** Contact

Until sajban has a working prototype, exchanges will be held in a room
on [[https://matrix.org][matrix.org]]:
- [[https://matrix.to/#/#sajban:matrix.org][#sajban:matrix.org]] for Sajban Space
- [[https://matrix.to/#/#sajban-blog:matrix.org][#sajban-blog:matrix.org]] for read-only minimal feed  
- [[https://matrix.to/#/#sajban-dev:matrix.org][#sajban-dev:matrix.org]] for development-related talk
