[package]
name = "krios"
version = "0.1.0"
authors = ["li <@li:maisiliym.uniks>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sajban = { version = "*", features = [], path = "../" }
